### ISSUE TITLE
Doesnt work in all major A-browsers.

### ISSUE THREAD

**Issue by ghost** [adeelejaz/jquery-image-resize#1]
works in chrome 6beta. And in Firefox 3.6.8 but it's buggy - at the first pageload the images arent resized. Doesnt work at all in IE8 + IE8 Compatibility mode. Havent tested other browsers. Just thought id let u know. :)

**Comment by adeelejaz** [comment]
In trying to fix webkit browsers, I destroyed Gecko :) I'll have the fix uploaded in a few hours. Thanks for pointing the issue out.

**Comment by adeelejaz** [comment]
Fixed
