### ISSUE TITLE
Question - does this resize images client side before they are posted?

### ISSUE THREAD

**Issue by pmsteil** [adeelejaz/jquery-image-resize#10]
I want to have a form to allow a user to submit a photo, crop it and submit only the cropped image...

Is this possible with your code?

Thanks!
Patrick

**Comment by pmsteil** [comment]
Oh and one other thing, if the image is mega huge, we want to force a resize to a minimum width/height... is that possible?

Thanks!

**Comment by adeelejaz** [comment]
For your first question, nope, this plugin is more a client-side resizing or down scaling plugin.

As for your answer to second question, the plugin takes a maximum height and a maximum width and the image is resized to fit in that.
