### ISSUE TITLE
jQuery 1.9.1 Compatibility issue

### ISSUE THREAD

**Issue by phena109** [adeelejaz/jquery-image-resize#11]
I think you already noticed what from jQuery 1.9 they have the $.browser variable removed. ae will throw error and so not useable since that version.

**Comment by adeelejaz** [comment]
I did make gist just for that: https://gist.github.com/adeelejaz/4714079

I'll try to roll out a new version on weekend that incorporates the $.browser

**Comment by jeroen** [comment]
Just update your jquery source in the example to use the old version of jquery: http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js

**Comment by adeelejaz** [comment]
This should be fixed with v2.1.3
