### ISSUE TITLE
no method 'aeImageResize' 

### ISSUE THREAD

**Issue by Kaby** [adeelejaz/jquery-image-resize#13]
Hi,

Hope you are still around.

Have an issue and get that error messgae:

"Uncaught TypeError: Object [object Object] has no method 'aeImageResize' "
I'm working on wordpress, paid attention to js files call order, just copy-pasted the function call from your doc : "$('.resizeme').aeImageResize", and added the resizeme class to my <img> but still have this error. Any requirement I could have forget ?

I am dynamicly giving the src to my <img class="resizeme"> from an other dom elemnt if it can helps.

Thaks for any help

**Comment by adeelejaz** [comment]
Yep, still alive and kicking :)

The error seems to point towards the plugin file not being included. Have you included the jquery.ae.image.resize.min.js file? Please make sure it is appears in the HTML below the jQuery file. Is it possible for me to have a look?

**Comment by Kaby** [comment]
Hey ! thanks for the quick reply ! Actually yes I included the jquery.ae.image.resize.min.js file: I see it in the head and have an error when I delete a ";" or so...

I have nothing online to show yet, and I think I'll use css property min-height for now as I have no issue yet with that full css solution wich seems to be enough for my need (and because this uncaught error made me crazy)

Anyway thanks for your reply and sorry about using your time when I went for an other solution.

Thanks aswell for offering public plugins I really admire it as a junior developper.

Best regards

**Comment by adeelejaz** [comment]
If you don't care about IE6 support then I highly recommend the CSS version here:
http://adeelejaz.com/blog/resize-image-without-using-javascript-or-jquery/

**Comment by lesagefarid** [comment]
I try  jquery.ae.image.resize, i was satisfied about until i do refresh page. When i refresh the page the jquery code don't recognize the plugin.
msg error: ae.image.resize unknown

All is fine when i run the code but wen I make refresh from the four browser(ie, chrome, firefox & opera).
![capture](https://cloud.githubusercontent.com/assets/3193942/5189957/ccdd21b4-74d9-11e4-8347-1374c69c0853.PNG)

code:

``` javascript
 var wWidth, hHeight;
            var path = window.location.href;
            var file = path.substring(path.lastIndexOf("/") + 1, path.legth);
            path = path.replace(file, 'ImgstxtTab/imgs');
            var extImgLow = ".jpg";
            var wImg, hImg, ref, ratio = 0;
            $.ajax({
                url: path,
                async: false,
                success: function (data) {
                    $("#tThumbnail").empty();
                    $(data).find('a:contains(' + extImgLow + ')').each(function (index, value) {
                        var imgPath = path + "/tab" + parseInt(index + 1) + ".jpg";
                        var id = '"img' + parseInt(index + 1) + '"';
                        var img = $("<img />").attr('src', imgPath)
                            .load(function () {
                                if (!this.complete || typeof this.naturalWidth == "undefined" || this.naturalWidth == 0) {
                                    setPageError("Tableaux getImages", "index.html", "Image incorrect!");
                                    return false;
                                } else {
                                    wWidth = this.naturalWidth;
                                    hHeight = this.naturalHeight;
                                    ratio = wWidth / hHeight;
                                    if (wWidth > hHeight) { wImg = '150px;'; hImg='130px;'; }
                                    else if (wWidth < hHeight) {wImg = '110px;';hImg = '150px;';}
                                    else if (wWidth == hHeight) {wImg = '150px;';hImg = '150px;';}
                                }
                                var row = '<tr><td><img id=' + id + ' src="' + imgPath +
                                    '" style="width:' +wImg + 'height:'+hImg + 'marging-top:2px;cursor:pointer;"' +
                                    ' data-width=' + this.naturalWidth + ' data-height=' + this.naturalHeight +
                                    '/></td></tr>';
  console.log(row);
                                $("#tThumbnail").append(row);
                                $("#divdDetails").load("ImgstxtTab/txt/tab1.html", function (responseTxt, statusTxt, xhr) {
                                    if (statusTxt == "success") {
                                        $("#divdDetails").show();
                                    }
                                    else {
                                        setPageError("Tableaux Load tab1.html", "index.html", xhr.status + ": " + xhr.statusText + "\n" + path)
                                    }
                                });

                                var selector = $("#tThumbnail").find('img');
                                selector.aeImageResize({width:150, height:150});
                                $("#imgZoom").attr('src', selector.attr('src'));
                                $("#divPlayer").attr('width', this.naturalWidth);
                                $("#divPlayer").attr('height', this.naturalHeight);
                                $("#divPlayer").show();
                                $("#imgZoom").attr('width', this.naturalWidth);
                                $("#imgZoom").attr('height', this.naturalHeight);
                                $("#imgZoom").show({ effect: 'drop', duration: 1000 });
                            });//load(function ()
                    });//each(function (index, value)
                }, //success

                error: function (err) {
                    setPageError("Tableaux getImages", "index.html", xhr.status + ": " + xhr.statusText )
                }
            });
```

**Comment by adeelejaz** [comment]
This isn't an issue with the script but the actual way you are including the jQuery and my plugin on the page. Can you please post the <script src="..."></script> tags? Specifically in the order they are included on the website.

Can you also confirm you are getting this error on Chrome and Firefox when you refresh? Or is this for IE only?

**Comment by lesagefarid** [comment]
ok I tested under (ie, safari , chrome, firefox & opera)
the plugin don't work only in IE11.
NB: script loaded:

``` html
    <script type="text/javascript" src="scripts/master.js"></script>  //mine js
    <script type="text/javascript" src="scripts/jquery-2.0.3.min.js"></script>
    <script type="text/javascript" src="scripts/jquery-ui-1.11.2.js"></script>
    <script type="text/javascript" src="scripts/jquery.ae.image.resize.js"></script>
```

I am inserting console. in my code to evaluate why that happend in IE.
hope to find this I will feddback.
Thank for your quick response.

**Comment by lesagefarid** [comment]
script order:
 src="scripts/master.js"  //this my js
src="scripts/jquery-2.0.3.min.js
src="scripts/jquery-ui-1.11.2.js"
 src="scripts/jquery.ae.image.resize.js"
It seams that the last comment din't accept the tag script.

**Comment by adeelejaz** [comment]
Can you move try by moving your script, master.js below the library? The reason behind is that when you when you reload the page, the scripts are fetched from the cache and the master.js can fire before the others scripts are loaded.

The code you posted, is it in the master.js file?

**Comment by lesagefarid** [comment]
Yes that's fine. I tested again from all browsers and specially three times with ie.
I appreciate your plugin, its save a lot of work.
Many thanks for your help.
