### ISSUE TITLE
return width and height

### ISSUE THREAD

**Issue by xrmx** [adeelejaz/jquery-image-resize#5]
It would be nice if the plugin would return an object with the new width and height values set to the image, so if you want to use the updated size of the image you don't have to query it again.

**Comment by adeelejaz** [comment]
The plugin can accept an array of images and each of those images can be resized differently. For example, if I had two images of 200px x 350px and 250px x 300px which I just resized into a square of 250px x 250px. Each of those images dimensions will different.

**Comment by xrmx** [comment]
What about an array of objects? Anyway this is just a feature request, no big deal.

**Comment by adeelejaz** [comment]
Returning an array of objects will break chaining, which I think is far more useful. How about a flag that you have to set to return array objects instead of jQuery object?

**Comment by xrmx** [comment]
Thanks, but really it's not that important, it's fine for me to query for the size again. Really don't like adding flags for obscure use cases :)
