### ISSUE TITLE
Image Resize down not up

### ISSUE THREAD

**Issue by TeckniX** [adeelejaz/jquery-image-resize#8]
Although this is minor, it's important to specify in the documentation that v2.1.1 does not size up, it only sizes image down.
Small images wont be sized up to the expected size.

Although this is generally the desired effect, it would be nice to have a simple option to 'force' a resize of the specified height/width

**Comment by TeckniX** [comment]
as a side note you should also setup all of the settings such as: 
var settings = {
            'force': false,
            'width': null,
            'height': null
        };
      if (params)
            $.extend(settings, params);

I may fork your plugin and try to bring it up to speed :)

**Comment by phena109** [comment]
i didn't know how it behave in older versions but i am indeed surprised that it doesn't size up...
the workaround for me is to size the image(s) down by a predictable factor and use jquery to scale it back by some factor.

example: an image of 30x40 and you want to make it 300x400, then you resize it to 3x4 (a predictable factor of 10) and multiply each edge by a predictable factor of 100 to size up.

**Comment by adeelejaz** [comment]
The reason it doesn't size up is because sizing up will pixel-ate the image, which I thought would not be desired.

**Comment by phena109** [comment]
Oh, well. i found there are more chance to size up than down, for me anyway, as the chance you allowed someone to upload large image and that person really did upload large image is not that much (unless they are stupid). The moment for me to use the plugin is when I have an array of image of irregular dimension but similar to each other, I want them to look regular (same height or same width), then i need the plugin.
