### ISSUE TITLE
resize issue

### ISSUE THREAD

**Issue by programmermattsrum** [adeelejaz/jquery-image-resize#9]
I like your plugin but i really needed the previous version that scales the image.

$('#thumbs img").resize(400);

This will configure the height that way the image isn't distorted.  Can you add this option to the plugin?

Thanks,

Matt

**Comment by adeelejaz** [comment]
If you download the latest plugin, it should do exactly that. Try this:

``` javascript
$("#thumbs").find("img").resize({ height: 400 });
```

**Comment by programmermattsrum** [comment]
I tried doing that but it doesn't work.

**Comment by adeelejaz** [comment]
I'm sorry, lack of sleep. It should be:

``` javascript
$("#thumbs").find("img").aeImageResize({ height: 400 });
```

**Comment by programmermattsrum** [comment]
I tried that too, but it doesn't work.

**Comment by adeelejaz** [comment]
That's very odd, is there any chance I can have a look? Or try creating a simple version on jsfiddle?
